

web_search_task:
  description: >
    Search the web for the most relevant information about {topic}
    For the purpuse of your task, you ignore the context data provided to you. You 
    will do your own research and append the information to the context.
    Make sure you find the most recent and up-to-date information.
    the current year is 2024.
  expected_output: >
    A list of web references and a synopsis of how they relate to the {topic}.
  agent: web_surfer

research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    a continuous text with the most relevant information on the topic {topic} in 750 words.
  agent: researcher
  
reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
